### ISSUE TITLE
DerStandard Dataset

### ISSUE THREAD

**Issue by julfr** [Dennis1989/RP-Mod-RP-Crowd#1]
Hi, thank you for your project!
Do I need to load the DerStandard dataset myself in `Dataset/Text-Data`?

**Comment by julfr** [comment]
Hi, thank you for your project!
Do I need to load the DerStandard dataset myself in `Dataset/Text-Data`?

**Comment by Dennis1989** [comment]
Hey there. As you can see, we already uploaded the preprocessed dataset in this subfolder as `derstandard.csv` and `derstandard-folds.csv`, respectively. You can also download the file from their site (https://ofai.github.io/million-post-corpus/) and then preprocess the dataset we described in our readme (since we had to modify and adjust their labeling schema to transform it into a binary problem).

I hope this helps :)

**Comment by julfr** [comment]
Thanks for response.
Yes I saw `derstandard.csv`. As I tried to run `Dataset Creation.ipynb` I saw, that I don't have 'derstandard_abusive.csv' and 'derstandard_non_abusive.csv' in the `/Dataset/Text-Data/` folder. So I need to download and preprocess them myself.
